title: Gu10285's Homepage
page-top-title: Gu10285
top-section-bg-text: Communication Engineering
home-subtitle: Gu10285&ensp;|&ensp;清风明月已不在
copyright-text: '&copy; Gu10285 2024-2025. All Rights Reserved.'
